security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [Client, User]
        Client:
            entity: { class: App\Entity\Client, property: Username}
        User:
            entity: { class: App\Entity\User, property: username}
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            logout:
                path: /logout
                target: /
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                check_path: login
                provider: chain_provider
            # https://symfony.com/doc/current/security/form_login_setup.html

#        api:
            # activate different ways to authenticate
#            logout:
#                path: /logout
#                target: /

#            form_login:
#                check_path: login
#                provider: Client

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
       # - { path: ^/profile, roles: ROLE_USER }

    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
        App\Entity\Client:
            algorithm: bcrypt
            cost: 12